[package]
name = "chakracore"
version = "0.1.0"
authors = ["Sankha Narayan Guria <sankha93@gmail.com>"]
license = "MIT"
description = "ChakraCore bindings for Rust"

[lib]
name = "chakracore"
path = "src/lib.rs"
test = true
doc = true

[dependencies]
libc = "0.2.0"
encoding = "0.2"
